/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   lipsum.h                                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: kblanche <kblanche@42angouleme.fr>         +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/10/23 17:24:03 by kblanche          #+#    #+#             */
/*   Updated: 2025/10/23 17:29:03 by kblanche         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#define LIPSUM2048 "Praesent feugiat, felis at mollis interdum, ante nibh lacinia turpis, in feugiat tortor nulla eu orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris placerat magna euismod ornare finibus. Curabitur malesuada interdum aliquet. Suspendisse blandit justo nec augue venenatis feugiat. Phasellus accumsan magna id justo tristique facilisis a non magna. Donec auctor, lacus nec facilisis molestie, tortor nisl ornare justo, elementum laoreet diam ex vel quam. Duis mollis dui pharetra urna finibus convallis. Nunc at augue nisl. Duis porttitor, magna eu elementum porttitor, neque massa euismod velit, ac lobortis lorem erat non lectus. Vivamus non nibh ut elit dignissim imperdiet id vel nisl. Sed luctus dapibus ipsum dictum dignissim. Aliquam erat volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae. Ut in erat augue. Aliquam sed libero a eros mollis blandit. Aenean molestie lectus non est porta interdum. Integer ut nunc ipsum. Donec eu quam purus. Fusce elementum laoreet felis non consequat. Pellentesque feugiat, lacus non pellentesque aliquam, quam orci feugiat urna, fermentum mattis libero tellus ac tortor. Aliquam erat volutpat. Aenean consequat nibh ac nisi dapibus, non pellentesque leo finibus. Donec lacinia ante eget nulla egestas, quis fringilla lorem scelerisque. Donec nec finibus justo. Morbi ultrices semper tristique. Morbi at iaculis ipsum. Maecenas aliquam mi eu risus mollis egestas. Vivamus ullamcorper ex nec lectus imperdiet auctor. Praesent a ultricies elit. Donec rutrum sapien quis est dictum facilisis ac et nisi. Vivamus porttitor enim at eleifend porttitor ipsum nulla vestibulum nisi, venenatis convallis arcu nisi sed mauris. Sed ipsum erat, malesuada id nulla at, varius venenatis turpis. Maecenas ut porttitor urna, sit amet dignissim est. Sed id pellentesque ipsum, sit amet sollicitudin metus. Pellentesque in arcu tellus. Ut pretium dignissim justo at dignissim. Quisque faucibus dolor et orci sollicitudin accumsan."
